server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:fiadopay;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:


logging:
  file:
    name: app.logs
  level:
    root: INFO

  jpa:
    hibernate:
      ddl-auto: update


  h2:
    console:
      enabled: true
      path: /h2

fiadopay:
  webhook-secret: ucsal-2025
  processing-delay-ms: 1500
  failure-rate: 0.15

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: kg2OTmb0NRhLzS7ZfluwbEkU4cJNcC0jPVnmJCUrvUiieRUhB21WCG2g6d6n8GW3
